conf = {}
conf['sprites'] = {}
conf['sprites'][0] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][1] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][2] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][3] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][4] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][5] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][6] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][7] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][8] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][9] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][10] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][11] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][12] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][13] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][14] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][15] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][16] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][17] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][18] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][19] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][20] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][21] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][22] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][23] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][24] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][25] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][26] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][27] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][28] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][29] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][30] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][31] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][32] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][33] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][34] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][35] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][36] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][37] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][38] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][39] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][40] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][41] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][42] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][43] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][44] = {'type' : 'music', 'data' : None, 'description' : ''}
conf['sprites'][45] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][46] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][47] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][48] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][49] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][50] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][51] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][52] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][53] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][54] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][55] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][56] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][57] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][58] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][59] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][60] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][61] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][62] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][63] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][64] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][65] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][66] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][67] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][68] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][69] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][70] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][71] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][72] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][73] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][74] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][75] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][76] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][77] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][78] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][79] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][80] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][81] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][82] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][83] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][84] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][85] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][86] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][87] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][88] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][89] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][90] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][91] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][92] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][93] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][94] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][95] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][96] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][97] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][98] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][99] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][100] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][101] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][102] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][103] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][104] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][105] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][106] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][107] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][108] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][109] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][110] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][111] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][112] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][113] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][114] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][115] = {'type' : 'visual', 'data' : None, 'description' : ''}
conf['sprites'][116] = {'type' : 'passable', 'data' : None, 'description' : ''}
conf['sprites'][117] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 1"}
conf['sprites'][118] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 1"}
conf['sprites'][119] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 2"}
conf['sprites'][120] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 2"}
conf['sprites'][121] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 3"}
conf['sprites'][122] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 3"}
conf['sprites'][123] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 4"}
conf['sprites'][124] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 4"}
conf['sprites'][125] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 5"}
conf['sprites'][126] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 5"}
conf['sprites'][127] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 6"}
conf['sprites'][128] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 6"}
conf['sprites'][129] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 7"}
conf['sprites'][130] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 7"}
conf['sprites'][131] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 8"}
conf['sprites'][132] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 8"}
conf['sprites'][133] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 9"}
conf['sprites'][134] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 9"}
conf['sprites'][135] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 10"}
conf['sprites'][136] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 10"}
conf['sprites'][137] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 11"}
conf['sprites'][138] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 11"}
conf['sprites'][139] = {'type' : 'level_info', 'data' : None, 'description' : "Humans 12"}
conf['sprites'][140] = {'type' : 'level_info', 'data' : None, 'description' : "Orcs 12"}
conf['sprites'][141] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"}  
conf['sprites'][142] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"}  
conf['sprites'][143] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"}  
conf['sprites'][144] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"}  
conf['sprites'][145] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][146] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][147] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][148] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][149] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][150] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][151] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][152] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][153] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][154] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][155] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][156] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][157] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][158] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][159] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][160] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][161] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][162] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][163] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][164] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][165] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][166] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][167] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][168] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][169] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][170] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][171] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][172] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][173] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][174] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][175] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][176] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][177] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][178] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][179] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][180] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][181] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][182] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][183] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][184] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][185] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][186] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][187] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][188] = {'type' : 'level_info', 'data' : None, 'description' : "Unknown Level"} 
conf['sprites'][189] = {'type' : 'tile_set', 'data' : None, 'description' : "Summer 1"}
conf['sprites'][190] = {'type' : 'tiles', 'data' : None, 'description' : "Summer 2"}
conf['sprites'][191] = {'type' : 'file_palette_short', 'data' : None, 'description' : "Summer 3"}
conf['sprites'][192] = {'type' : 'tile_set', 'data' : None, 'description' : "Barrens 1"}
conf['sprites'][193] = {'type' : 'tiles', 'data' : None, 'description' : "Barrens 2"}
conf['sprites'][194] = {'type' : 'file_palette_short', 'data' : None, 'description' : "Barrens 3"}
conf['sprites'][195] = {'type' : 'tile_set', 'data' : None, 'description' : "Dungeon 1"}
conf['sprites'][196] = {'type' : 'tiles', 'data' : None, 'description' : "Dungeon 2"}
conf['sprites'][197] = {'type' : 'file_palette_short', 'data' : None, 'description' : "Dungeon 3"}
conf['sprites'][198] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 1"}
conf['sprites'][199] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 2"}
conf['sprites'][200] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 3"}
conf['sprites'][201] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 4"}
conf['sprites'][202] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 5"}
conf['sprites'][203] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 6"}
conf['sprites'][204] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 7"}
conf['sprites'][205] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 8"}
conf['sprites'][206] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 9"}
conf['sprites'][207] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 10"}
conf['sprites'][208] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 11"}
conf['sprites'][209] = {'type' : 'file_table', 'data' : None, 'description' : "Unknown Table 12"}
conf['sprites'][210] = {'type' : 'file_palette_short', 'data' : None, 'description' : "Unknown"}
conf['sprites'][211] = {'type' : 'file_palette_short', 'data' : None, 'description' : "Unknown"}
conf['sprites'][212] = {'type' : 'unknown', 'data' : None, 'description' : "Unknown"}
conf['sprites'][213] = {'type' : 'unknown', 'data' : None, 'description' : "Unknown"}
conf['sprites'][214] = {'type' : 'unknown', 'data' : None, 'description' : "Unknown"}
conf['sprites'][215] = {'type' : 'unknown', 'data' : None, 'description' : "Unknown file (short, offset, 2x data PSQR) (P-splines via QR?)"}
conf['sprites'][216] = {'type' : 'image', 'data' : None, 'description' : "Background 'Blizzard'"}
conf['sprites'][217] = {'type' : 'palette', 'data' : None, 'description' : "For Background"}
conf['sprites'][218] = {'type' : 'image', 'data' : None, 'description' : "Topbar (Humans)"}
conf['sprites'][219] = {'type' : 'image', 'data' : None, 'description' : "Topbar (Orcs)"}
conf['sprites'][220] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Right (Humans)"}
conf['sprites'][221] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Right (Orcs)"}
conf['sprites'][222] = {'type' : 'image', 'data' : None, 'description' : "Lower Bar (Humans)"}
conf['sprites'][223] = {'type' : 'image', 'data' : None, 'description' : "Lower Bar (Orcs)"}
conf['sprites'][224] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Left Minimap Empty (Humans)"}
conf['sprites'][225] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Left Minimap Empty (Orcs)"}
conf['sprites'][226] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Left (Humans)"}
conf['sprites'][227] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Left (Orcs)"}
conf['sprites'][228] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Left Minimap Black (Humans)"}
conf['sprites'][229] = {'type' : 'image', 'data' : None, 'description' : "Sidebar Left Minimap Black (Orcs)"}
conf['sprites'][230] = {'type' : 'ui', 'data' : None, 'description' : "Warcraft CD"}
conf['sprites'][231] = {'type' : 'ui', 'data' : None, 'description' : "Purchase the Retail Version of Warcraft"}
conf['sprites'][232] = {'type' : 'ui', 'data' : None, 'description' : "Purchase the Retail Version of Warcraft"}
conf['sprites'][233] = {'type' : 'image', 'data' : None, 'description' : "Large Box (Humans)"}
conf['sprites'][234] = {'type' : 'image', 'data' : None, 'description' : "Large Box (Orcs)"}
conf['sprites'][235] = {'type' : 'image', 'data' : None, 'description' : "Small Box (Humans)"}
conf['sprites'][236] = {'type' : 'image', 'data' : None, 'description' : "Small Box (Orcs)"}
conf['sprites'][237] = {'type' : 'image', 'data' : None, 'description' : "Large Button"}
conf['sprites'][238] = {'type' : 'image', 'data' : None, 'description' : "Large Button (Clicked)"}
conf['sprites'][239] = {'type' : 'image', 'data' : None, 'description' : "Medium Button"}
conf['sprites'][240] = {'type' : 'image', 'data' : None, 'description' : "Medium Button (Clicked)"}
conf['sprites'][241] = {'type' : 'image', 'data' : None, 'description' : "Small Button"}
conf['sprites'][242] = {'type' : 'image', 'data' : None, 'description' : "Small Button (Clicked)"}
conf['sprites'][243] = {'type' : 'image', 'data' : None, 'description' : "Mainmenu Background Lower Part"}
conf['sprites'][244] = {'type' : 'image', 'data' : None, 'description' : "Button Arrow Left"}
conf['sprites'][245] = {'type' : 'image', 'data' : None, 'description' : "Button Arrow Left, Grey"}
conf['sprites'][246] = {'type' : 'image', 'data' : None, 'description' : "Button Arrow Right"}
conf['sprites'][247] = {'type' : 'image', 'data' : None, 'description' : "Button Arrow Right, Grey"}
conf['sprites'][248] = {'type' : 'image', 'data' : None, 'description' : "Window Border"}
conf['sprites'][249] = {'type' : 'image', 'data' : None, 'description' : "Saving/Loading Screen (Humans)"}
conf['sprites'][250] = {'type' : 'image', 'data' : None, 'description' : "Saving/Loading Screen (Orcs)"}
conf['sprites'][251] = {'type' : 'palette', 'data' : None, 'description' : "Unknown"}
conf['sprites'][252] = {'type' : 'palette', 'data' : None, 'description' : "Unknown"}
conf['sprites'][253] = {'type' : 'palette', 'data' : None, 'description' : "Unknown"}
conf['sprites'][254] = {'type' : 'image', 'data' : None, 'description' : "Hot keys"}
conf['sprites'][255] = {'type' : 'palette', 'data' : None, 'description' : "Humans"}
conf['sprites'][256] = {'type' : 'image', 'data' : None, 'description' : "Button 'ok'"}
conf['sprites'][257] = {'type' : 'image', 'data' : None, 'description' : "Button 'ok' 2"}
conf['sprites'][258] = {'type' : 'image', 'data' : None, 'description' : "Text 'WarCraft'"}
conf['sprites'][259] = {'type' : 'ui', 'data' : None, 'description' : "Main Menu Text"}
conf['sprites'][260] = {'type' : 'palette', 'data' : None, 'description' : "UI Palette"}
conf['sprites'][261] = {'type' : 'image', 'data' : None, 'description' : "Mainmenu Background"}
conf['sprites'][262] = {'type' : 'palette', 'data' : None, 'description' : "Pointer Palette"}
conf['sprites'][263] = {'type' : 'cursor', 'data' : None, 'description' : "Normal Pointer"}
conf['sprites'][264] = {'type' : 'cursor', 'data' : None, 'description' : "Not allowed"}
conf['sprites'][265] = {'type' : 'cursor', 'data' : None, 'description' : "Crosshair Orange"}
conf['sprites'][266] = {'type' : 'cursor', 'data' : None, 'description' : "Crosshair Red"}
conf['sprites'][267] = {'type' : 'cursor', 'data' : None, 'description' : "Crosshair Orange 2"}
conf['sprites'][268] = {'type' : 'cursor', 'data' : None, 'description' : "Magnifier"}
conf['sprites'][269] = {'type' : 'cursor', 'data' : None, 'description' : "Crosshair Green"}
conf['sprites'][270] = {'type' : 'cursor', 'data' : None, 'description' : "Loading..."}
conf['sprites'][271] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Top"}
conf['sprites'][272] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Topright"}
conf['sprites'][273] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Right"}
conf['sprites'][274] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Bottomright"}
conf['sprites'][275] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Bottom"}
conf['sprites'][276] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Bottomleft"}
conf['sprites'][277] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Left"}
conf['sprites'][278] = {'type' : 'cursor', 'data' : None, 'description' : "Scroll Topleft"}
conf['sprites'][279] = {'type' : 'sprite', 'data' : None, 'description' : "Human Warrior"}
conf['sprites'][280] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Grunt"}
conf['sprites'][281] = {'type' : 'sprite', 'data' : None, 'description' : "Human Peasant"}
conf['sprites'][282] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Peon"}
conf['sprites'][283] = {'type' : 'sprite', 'data' : None, 'description' : "Human Catapult"}
conf['sprites'][284] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Catapult"}
conf['sprites'][285] = {'type' : 'sprite', 'data' : None, 'description' : "Human Knight"}
conf['sprites'][286] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Rider"}
conf['sprites'][287] = {'type' : 'sprite', 'data' : None, 'description' : "Human Bowman"}
conf['sprites'][288] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Axethrower"}
conf['sprites'][289] = {'type' : 'sprite', 'data' : None, 'description' : "Human Wizard"}
conf['sprites'][290] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Wizard"}
conf['sprites'][291] = {'type' : 'sprite', 'data' : None, 'description' : "Human Priest"}
conf['sprites'][292] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Necro"}
conf['sprites'][293] = {'type' : 'sprite', 'data' : None, 'description' : "Medivh"}
conf['sprites'][294] = {'type' : 'sprite', 'data' : None, 'description' : "Lothar"}
conf['sprites'][295] = {'type' : 'sprite', 'data' : None, 'description' : "Wounded"}
conf['sprites'][296] = {'type' : 'sprite', 'data' : None, 'description' : "Garana"}
conf['sprites'][297] = {'type' : 'sprite', 'data' : None, 'description' : "Giant"}
conf['sprites'][298] = {'type' : 'sprite', 'data' : None, 'description' : "Spider"}
conf['sprites'][299] = {'type' : 'sprite', 'data' : None, 'description' : "Slime"}
conf['sprites'][300] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_300"}
conf['sprites'][301] = {'type' : 'sprite', 'data' : None, 'description' : "Scorpion"}
conf['sprites'][302] = {'type' : 'sprite', 'data' : None, 'description' : "Brigand"}
conf['sprites'][303] = {'type' : 'sprite', 'data' : None, 'description' : "Skeleton"}
conf['sprites'][304] = {'type' : 'sprite', 'data' : None, 'description' : "Skeleton 2"}
conf['sprites'][305] = {'type' : 'sprite', 'data' : None, 'description' : "Demon"}
conf['sprites'][306] = {'type' : 'sprite', 'data' : None, 'description' : "Water Elemental"}
conf['sprites'][307] = {'type' : 'sprite', 'data' : None, 'description' : "Human Farm"}
conf['sprites'][308] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Farm"}
conf['sprites'][309] = {'type' : 'sprite', 'data' : None, 'description' : "Human Barracks"}
conf['sprites'][310] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Barracks"}
conf['sprites'][311] = {'type' : 'sprite', 'data' : None, 'description' : "Human Church"}
conf['sprites'][312] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Stone Circle"}
conf['sprites'][313] = {'type' : 'sprite', 'data' : None, 'description' : "Human Tower"}
conf['sprites'][314] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Skull"}
conf['sprites'][315] = {'type' : 'sprite', 'data' : None, 'description' : "Human Base"}
conf['sprites'][316] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Base"}
conf['sprites'][317] = {'type' : 'sprite', 'data' : None, 'description' : "Human Smith"}
conf['sprites'][318] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Smith"}
conf['sprites'][319] = {'type' : 'sprite', 'data' : None, 'description' : "Human Stables"}
conf['sprites'][320] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Stables"}
conf['sprites'][321] = {'type' : 'sprite', 'data' : None, 'description' : "Human Smith"}
conf['sprites'][322] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Smith"}
conf['sprites'][323] = {'type' : 'sprite', 'data' : None, 'description' : "Stormwind"}
conf['sprites'][324] = {'type' : 'sprite', 'data' : None, 'description' : "Black Spire"}
conf['sprites'][325] = {'type' : 'sprite', 'data' : None, 'description' : "Goldmine"}
conf['sprites'][326] = {'type' : 'sprite', 'data' : None, 'description' : "Corpse"}
conf['sprites'][327] = {'type' : 'sprite', 'data' : None, 'description' : "Human Peasant with Lumber"}
conf['sprites'][328] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Peon with Lumber"}
conf['sprites'][329] = {'type' : 'sprite', 'data' : None, 'description' : "Human Peasant with Gold"}
conf['sprites'][330] = {'type' : 'sprite', 'data' : None, 'description' : "Orc Peon with Gold"}
conf['sprites'][331] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction"}
conf['sprites'][332] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction"}
conf['sprites'][333] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction 2"}
conf['sprites'][334] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction 2"}
conf['sprites'][335] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction 3"}
conf['sprites'][336] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction 3"}
conf['sprites'][337] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction 4"}
conf['sprites'][338] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction 4"}
conf['sprites'][339] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction 5"}
conf['sprites'][340] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction 5"}
conf['sprites'][341] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction 6"}
conf['sprites'][342] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction 6"}
conf['sprites'][343] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction 7"}
conf['sprites'][344] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction 7"}
conf['sprites'][345] = {'type' : 'sprite', 'data' : None, 'description' : "Humans Under construction 8"}
conf['sprites'][346] = {'type' : 'sprite', 'data' : None, 'description' : "Orcs Under construction 8"}
conf['sprites'][347] = {'type' : 'sprite', 'data' : None, 'description' : "Building explosion"}
conf['sprites'][348] = {'type' : 'sprite', 'data' : None, 'description' : "Fireball"}
conf['sprites'][349] = {'type' : 'sprite', 'data' : None, 'description' : "Arrow"}
conf['sprites'][350] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_350"}
conf['sprites'][351] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_351"}
conf['sprites'][352] = {'type' : 'sprite', 'data' : None, 'description' : "Tornado"}
conf['sprites'][353] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_353"}
conf['sprites'][354] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_354"}
conf['sprites'][355] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_355"}
conf['sprites'][356] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_356"}
conf['sprites'][357] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_357"}
conf['sprites'][358] = {'type' : 'sprite', 'data' : None, 'description' : "Unit_358"}
conf['sprites'][359] = {'type' : 'sprite', 'data' : None, 'description' : "UI Pictures Orcs"}
conf['sprites'][360] = {'type' : 'sprite', 'data' : None, 'description' : "UI Pictures Humans"}
conf['sprites'][361] = {'type' : 'sprite', 'data' : None, 'description' : "UI Pictures Icons"}
conf['sprites'][362] = {'type' : 'image', 'data' : None, 'description' : "Menu Button"}
conf['sprites'][363] = {'type' : 'image', 'data' : None, 'description' : "Menu Button (Pressed)"}
conf['sprites'][364] = {'type' : 'image', 'data' : None, 'description' : "Empty Button"}
conf['sprites'][365] = {'type' : 'image', 'data' : None, 'description' : "Empty Button (Pressed)"}
conf['sprites'][366] = {'type' : 'ui', 'data' : None, 'description' : "Remote system is not responding"}
conf['sprites'][367] = {'type' : 'ui', 'data' : None, 'description' : "Remote system is not responding (+Save)"}
conf['sprites'][368] = {'type' : 'ui', 'data' : None, 'description' : "Save Game; Load Game; Options; ..."}
conf['sprites'][369] = {'type' : 'ui', 'data' : None, 'description' : "Save Game; Load Game; Options; ..."}
conf['sprites'][370] = {'type' : 'ui', 'data' : None, 'description' : "Empty slots ... loading"}
conf['sprites'][371] = {'type' : 'ui', 'data' : None, 'description' : "Empty slots ... loading"}
conf['sprites'][372] = {'type' : 'ui', 'data' : None, 'description' : "Ok; Cancel"}
conf['sprites'][373] = {'type' : 'ui', 'data' : None, 'description' : "Ok; Cancel"}
conf['sprites'][374] = {'type' : 'ui', 'data' : None, 'description' : "Ok; Cancel"}
conf['sprites'][375] = {'type' : 'ui', 'data' : None, 'description' : "Ok; Cancel"}
conf['sprites'][376] = {'type' : 'ui', 'data' : None, 'description' : "Options"}
conf['sprites'][377] = {'type' : 'ui', 'data' : None, 'description' : "Options"}
conf['sprites'][378] = {'type' : 'ui', 'data' : None, 'description' : "Select Game Type"}
conf['sprites'][379] = {'type' : 'ui', 'data' : None, 'description' : "Choose Campaign"}
conf['sprites'][380] = {'type' : 'ui', 'data' : None, 'description' : "CD needed for Multiplayer"}
conf['sprites'][381] = {'type' : 'ui', 'data' : None, 'description' : "Customize your Game"}
conf['sprites'][382] = {'type' : 'ui', 'data' : None, 'description' : "Set Map"}
conf['sprites'][383] = {'type' : 'ui', 'data' : None, 'description' : "Set Opponent"}
conf['sprites'][384] = {'type' : 'ui', 'data' : None, 'description' : "Modem Connection"}
conf['sprites'][385] = {'type' : 'ui', 'data' : None, 'description' : "Modem Setup"}
conf['sprites'][386] = {'type' : 'ui', 'data' : None, 'description' : "Direct connection"}
conf['sprites'][387] = {'type' : 'ui', 'data' : None, 'description' : "Network connection"}
conf['sprites'][388] = {'type' : 'ui', 'data' : None, 'description' : "Customize your game"}
conf['sprites'][389] = {'type' : 'ui', 'data' : None, 'description' : "[empty slot] Save Game"}
conf['sprites'][390] = {'type' : 'ui', 'data' : None, 'description' : "[empty slot] Save Game"}
conf['sprites'][391] = {'type' : 'ui', 'data' : None, 'description' : "Quit to DOS or Main Menu"}
conf['sprites'][392] = {'type' : 'ui', 'data' : None, 'description' : "Quit to DOS or Main Menu"}
conf['sprites'][393] = {'type' : 'ui', 'data' : None, 'description' : "Volume in drive C"}
conf['sprites'][394] = {'type' : 'ui', 'data' : None, 'description' : "Volume in drive C"}
conf['sprites'][395] = {'type' : 'ui', 'data' : None, 'description' : "Connecting ..."}
conf['sprites'][396] = {'type' : 'ui', 'data' : None, 'description' : "Set Army"}
conf['sprites'][397] = {'type' : 'ui', 'data' : None, 'description' : "Set Army"}
conf['sprites'][398] = {'type' : 'ui', 'data' : None, 'description' : "Set Army"}
conf['sprites'][399] = {'type' : 'ui', 'data' : None, 'description' : "Set Army"}
conf['sprites'][400] = {'type' : 'ui', 'data' : None, 'description' : "Set Army"}
conf['sprites'][401] = {'type' : 'ui', 'data' : None, 'description' : "Set Army"}
conf['sprites'][402] = {'type' : 'ui', 'data' : None, 'description' : "Master has control"}
conf['sprites'][403] = {'type' : 'ui', 'data' : None, 'description' : "Slave has control"}
conf['sprites'][404] = {'type' : 'ui', 'data' : None, 'description' : "Set Player Races"}
conf['sprites'][405] = {'type' : 'ui', 'data' : None, 'description' : "Set Player Races"}
conf['sprites'][406] = {'type' : 'image', 'data' : None, 'description' : "Gold (Humans)"}
conf['sprites'][407] = {'type' : 'image', 'data' : None, 'description' : "Lumber (Humans)"}
conf['sprites'][408] = {'type' : 'image', 'data' : None, 'description' : "Gold (Orcs)"}
conf['sprites'][409] = {'type' : 'image', 'data' : None, 'description' : "Lumber (Orcs)"}
conf['sprites'][410] = {'type' : 'image', 'data' : None, 'description' : "%complete"}
conf['sprites'][411] = {'type' : 'image', 'data' : None, 'description' : "Human point summary"}
conf['sprites'][412] = {'type' : 'image', 'data' : None, 'description' : "Orc point summary"}
conf['sprites'][413] = {'type' : 'palette', 'data' : None, 'description' : "Summary palette"}
conf['sprites'][414] = {'type' : 'palette', 'data' : None, 'description' : "Unknown pal"}
conf['sprites'][415] = {'type' : 'image', 'data' : None, 'description' : "Background Victory"}
conf['sprites'][416] = {'type' : 'palette', 'data' : None, 'description' : "for 415"}
conf['sprites'][417] = {'type' : 'image', 'data' : None, 'description' : "Background Defeat"}
conf['sprites'][418] = {'type' : 'palette', 'data' : None, 'description' : "for 417"}
conf['sprites'][419] = {'type' : 'image', 'data' : None, 'description' : "Victory Text"}
conf['sprites'][420] = {'type' : 'image', 'data' : None, 'description' : "Defeat Text"}
conf['sprites'][421] = {'type' : 'image', 'data' : None, 'description' : "Human Briefing"}
conf['sprites'][422] = {'type' : 'image', 'data' : None, 'description' : "Orc Briefing"}
conf['sprites'][423] = {'type' : 'palette', 'data' : None, 'description' : "Briefing Palette 1"}
conf['sprites'][424] = {'type' : 'palette', 'data' : None, 'description' : "Briefing Palette 2"}
conf['sprites'][425] = {'type' : 'sprite', 'data' : None, 'description' : "Burning Fire Anim"}
conf['sprites'][426] = {'type' : 'sprite', 'data' : None, 'description' : "Talking Orc Anim"}
conf['sprites'][427] = {'type' : 'sprite', 'data' : None, 'description' : "Talking Orc 2 Anim"}
conf['sprites'][428] = {'type' : 'sprite', 'data' : None, 'description' : "Eating Human Anim"}
conf['sprites'][429] = {'type' : 'sprite', 'data' : None, 'description' : "Human Wizard Anim"}
conf['sprites'][430] = {'type' : 'sprite', 'data' : None, 'description' : "Anim 1"}
conf['sprites'][431] = {'type' : 'sprite', 'data' : None, 'description' : "Anim 2"}
conf['sprites'][432] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 1"}
conf['sprites'][433] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 2"}
conf['sprites'][434] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 3"}
conf['sprites'][435] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 4"}
conf['sprites'][436] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 5"}
conf['sprites'][437] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 6"}
conf['sprites'][438] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 7"}
conf['sprites'][439] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 8"}
conf['sprites'][440] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 9"}
conf['sprites'][441] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 10"}
conf['sprites'][442] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 11"}
conf['sprites'][443] = {'type' : 'briefing', 'data' : None, 'description' : "Orcs 12"}
conf['sprites'][444] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 1"}
conf['sprites'][445] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 2"}
conf['sprites'][446] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 3"}
conf['sprites'][447] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 4"}
conf['sprites'][448] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 5"}
conf['sprites'][449] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 6"}
conf['sprites'][450] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 7"}
conf['sprites'][451] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 8"}
conf['sprites'][452] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 9"}
conf['sprites'][453] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 10"}
conf['sprites'][454] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 11"}
conf['sprites'][455] = {'type' : 'briefing', 'data' : None, 'description' : "Humans 12"}
conf['sprites'][456] = {'type' : 'image', 'data' : None, 'description' : "Human Win"}
conf['sprites'][457] = {'type' : 'palette', 'data' : None, 'description' : "for 456"}
conf['sprites'][458] = {'type' : 'image', 'data' : None, 'description' : "Orc Win"}
conf['sprites'][459] = {'type' : 'palette', 'data' : None, 'description' : "for 458"}
conf['sprites'][460] = {'type' : 'embedded_data', 'data' : None, 'description' : "Unknown embedded Data file (entry count, offsets, data)"}
conf['sprites'][461] = {'type' : 'text', 'data' : None, 'description' : "Endgametext: Humans 1"}
conf['sprites'][462] = {'type' : 'text', 'data' : None, 'description' : "Endgametext: Orcs 1"}
conf['sprites'][463] = {'type' : 'text', 'data' : None, 'description' : "Endgametext: Humans 2"}
conf['sprites'][464] = {'type' : 'text', 'data' : None, 'description' : "Endgametext: Orcs 2"}
conf['sprites'][465] = {'type' : 'text', 'data' : None, 'description' : "Credits"}
conf['sprites'][466] = {'type' : 'text', 'data' : None, 'description' : "Level won (Humans?)"}
conf['sprites'][467] = {'type' : 'text', 'data' : None, 'description' : "Level won (Orcs?)"}
conf['sprites'][468] = {'type' : 'text', 'data' : None, 'description' : "Level lost (Humans?)"}
conf['sprites'][469] = {'type' : 'text', 'data' : None, 'description' : "Level lost (Orcs?)"}
conf['sprites'][470] = {'type' : 'image', 'data' : None, 'description' : "Human Win/Animation 2"}
conf['sprites'][471] = {'type' : 'image', 'data' : None, 'description' : "Orc Win/Animation 2"}
conf['sprites'][472] = {'type' : 'wave', 'data' : None, 'description' : "Blizzard"}
conf['sprites'][473] = {'type' : 'wave', 'data' : None, 'description' : "Opening Gate"}
conf['sprites'][474] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][475] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][476] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][477] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][478] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][479] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][480] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][481] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][482] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][483] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][484] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][485] = {'type' : 'wave', 'data' : None, 'description' : "Clicking noise"}
conf['sprites'][486] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][487] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][488] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][489] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][490] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][491] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][492] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][493] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][494] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][495] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][496] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][497] = {'type' : 'wave', 'data' : None, 'description' : "The Orcs are approaching"}
conf['sprites'][498] = {'type' : 'wave', 'data' : None, 'description' : "There are enemies nearby"}
conf['sprites'][499] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][500] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][501] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][502] = {'type' : 'wave', 'data' : None, 'description' : "Work completed"}
conf['sprites'][503] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][504] = {'type' : 'wave', 'data' : None, 'description' : "They're destroying our city"}
conf['sprites'][505] = {'type' : 'wave', 'data' : None, 'description' : "We are under attack"}
conf['sprites'][506] = {'type' : 'wave', 'data' : None, 'description' : "The town is under attack"}
conf['sprites'][507] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][508] = {'type' : 'wave', 'data' : None, 'description' : "Your command"}
conf['sprites'][509] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][510] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][511] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][512] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][513] = {'type' : 'wave', 'data' : None, 'description' : "Yes"}
conf['sprites'][514] = {'type' : 'wave', 'data' : None, 'description' : "Yes, mylord"}
conf['sprites'][515] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][516] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][517] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][518] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][519] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][520] = {'type' : 'wave', 'data' : None, 'description' : "Yes?"}
conf['sprites'][521] = {'type' : 'wave', 'data' : None, 'description' : "Your will, sire?"}
conf['sprites'][522] = {'type' : 'wave', 'data' : None, 'description' : "Mylord?"}
conf['sprites'][523] = {'type' : 'wave', 'data' : None, 'description' : "My liege?"}
conf['sprites'][524] = {'type' : 'wave', 'data' : None, 'description' : "Your bidding?"}
conf['sprites'][525] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][526] = {'type' : 'VOC', 'data' : None, 'description' : "Unknown"}
conf['sprites'][527] = {'type' : 'wave', 'data' : None, 'description' : "Stop poking me"}
conf['sprites'][528] = {'type' : 'wave', 'data' : None, 'description' : "What?!"}
conf['sprites'][529] = {'type' : 'wave', 'data' : None, 'description' : "What do you want?!"}
conf['sprites'][530] = {'type' : 'wave', 'data' : None, 'description' : "Why do you keep touching me?!"}
conf['sprites'][531] = {'type' : 'wave', 'data' : None, 'description' : "Splatter"}
conf['sprites'][532] = {'type' : 'wave', 'data' : None, 'description' : "Spell"}
conf['sprites'][533] = {'type' : 'wave', 'data' : None, 'description' : "Placement"}
conf['sprites'][534] = {'type' : 'wave', 'data' : None, 'description' : "Orc Tower"}
conf['sprites'][535] = {'type' : 'wave', 'data' : None, 'description' : "Human Church"}
conf['sprites'][536] = {'type' : 'wave', 'data' : None, 'description' : "Kennel"}
conf['sprites'][537] = {'type' : 'wave', 'data' : None, 'description' : "Stables"}
conf['sprites'][538] = {'type' : 'wave', 'data' : None, 'description' : "Smith"}
conf['sprites'][539] = {'type' : 'wave', 'data' : None, 'description' : "Burning Fire"}
conf['sprites'][540] = {'type' : 'wave', 'data' : None, 'description' : "Boom"}
conf['sprites'][541] = {'type' : 'wave', 'data' : None, 'description' : "Boom2"}
conf['sprites'][542] = {'type' : 'wave', 'data' : None, 'description' : "Human Ending"}
conf['sprites'][543] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][544] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][545] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][546] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][547] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][548] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][549] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][550] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][551] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][552] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][553] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][554] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][555] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][556] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][557] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][558] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][559] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][560] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][561] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][562] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][563] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][564] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][565] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][566] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][567] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][568] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][569] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][570] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][571] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][572] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][573] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][574] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][575] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][576] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][577] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][578] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][579] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][580] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][581] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
conf['sprites'][582] = {'type' : 'wave', 'data' : None, 'description' : "Unknown"}
